version: '3.3'

services:
  app:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./app_files:/var/www/html
    ports:
      - "80:8000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Password123
  db:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Password123
      MYSQL_ROOT_PASSWORD: root_password
volumes:
  db_data:
  app_files:
